### ISSUE TITLE
Error al abrir el modal de "Ser Colaborador": se muestra como sección al final de la página

### ISSUE THREAD

**Issue by agusFIUNI** [IdealProject/ideal#18]
## Descripcion:

He encontrado un problema en la funcionalidad del botón "Ser Colaborador". Al hacer clic en este botón, en lugar de abrir un modal, se despliega como una sección más al final de la página. Esto sucede únicamente después de hacer clic en alguno de los botones del navbar, como "Ideal", "Comunidad", etc. Además, el scrollbar se deshabilita, impidiendo la navegación por la página.

### Pasos para reproducir el error:

1. Navegar a la página donde se encuentra el botón "Ser Colaborador".
2. Hacer clic en cualquiera de los botones del navbar (ej. "Ideal", "Comunidad").
3. Luego, hacer clic en "Ser Colaborador".

Adjunto imágenes tomadas desde mi teléfono y computadora que muestran el error y cómo se ve al recargar la misma página.

**Comportamiento esperado:** El botón debería abrir un modal donde se puedan rellenar los datos.
![image](https://github.com/user-attachments/assets/fbe3edf4-1c02-4624-945c-9dfc4b51c787)
![image](https://github.com/user-attachments/assets/b33a7bba-b636-4f84-937a-3afd969d8e36)

**Comportamiento observado:** El contenido del modal aparece como una sección al final de la página, y el scrollbar se deshabilita.
![image](https://github.com/user-attachments/assets/43a60490-06a4-4fa2-8c41-2abc64742f47)
![image](https://github.com/user-attachments/assets/9374ebc9-19af-48f7-9635-d50147abc197)
![image](https://github.com/user-attachments/assets/def61249-ce28-4cc0-8f93-89efdec17870)
![image](https://github.com/user-attachments/assets/e419e399-0598-4867-90da-bb3bacc421ae)

Este problema puede ocurrir en otras secciones, por lo que recomiendo revisarlo meticulosamente.
He probado el error en diferentes navegadores, incluyendo Chrome y Firefox, y el problema persiste en ambos.

¡Gracias por su atención a este problema! Espero que se pueda resolver pronto.

**Comment by geroxima** [comment]
Hola Agustin!

Gracias por tomarte el tiempo de reportar este bug con tanto detalle.

La funcionalidad del modal fue una implementación temporal para el evento de la ExpoInge 2024, con el objetivo de facilitar el acceso rápido al formulario desde la página principal. Esta funcionalidad fue removida, y ahora el botón "Ser Colaborador" redirige directamente al formulario en Tally: [https://tally.so/r/31lVzL](https://tally.so/r/31lVzL).  

Una vez completado el formulario, los usuarios son redirigidos automáticamente al sitio principal: [https://ideal.fiuni.edu.py/](https://ideal.fiuni.edu.py/).  

¡Agradecemos mucho tu ayuda en mejorar la plataforma!  

Saludos
